
type_map = {
    #mysql type     :  java type#
    "int"           :  "java.lang.Integer",
    "tinyint"       :  "java.lang.Integer",
    "smallint"      :  "java.lang.Integer",
    "mediumint"     :  "java.lang.Integer",
    "bigint"        :  "java.lang.Long",
    "char"          :  "java.lang.String",
    "varchar"       :  "java.lang.String",
    "text"          :  "java.lang.String",
    "time"          :  "java.util.Date",
    "datetime"      :  "java.util.Date",
    "float"         :  "java.lang.Float",
    "double"        :  "java.lang.Double",
    "decimal"       :  "java.lang.Double",
    "tinytext"      :  "java.lang.String",
    "mediumtext"    :  "java.lang.String",
    "longtext"      :  "java.lang.String",
    "timestamp"     :  "java.util.Date",
}

type_map_sample = {
    "int"           :  "Integer",
    "tinyint"       :  "Integer",
    "smallint"      :  "Integer",
    "mediumint"     :  "Integer",
    "bigint"        :  "Long",
    "char"          :  "String",
    "varchar"       :  "String",
    "text"          :  "String",
    "time"          :  "Date",
    "datetime"      :  "Date",
    "float"         :  "Float",
    "double"        :  "Double",
    "decimal"       :  "Double",
    "tinytext"      :  "String",
    "mediumtext"    :  "String",
    "longtext"      :  "String",
    "timestamp"     :  "Date",
}